name: SonarQube Analysis

on:
  push:
    branches:
      - main  # of de branch waarop je de analyse wilt uitvoeren

jobs:
  sonarcloud:
    name: Run SonarQube Scanner with Docker
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run SonarScanner in Docker
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
        SONAR_ORG_KEY: ${{ secrets.SONAR_ORG }}
        SONAR_HOST_URL: "https://sonarcloud.io"
      run: |
        docker run \
          --rm \
          -e SONAR_HOST_URL="https://sonarcloud.io" \
          -e SONAR_TOKEN="${secrets.SONAR_TOKEN}" \
          -e SONAR_PROJECT_KEY="${secrets.SONAR_PROJECT_KEY}" \
          -e SONAR_ORG_KEY="${secretsSONAR_ORG}" \
          -v "${GITHUB_WORKSPACE}:/usr/src" \
          sonarsource/sonar-scanner-cli
