name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    name: SonarCloud analysis
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: '17'

    - name: Install compatible SonarScanner
      run: |
        curl -sS https://github.com/SonarSource/sonar-scanner-cli/releases/download/4.6.2.2472/sonar-scanner-cli-4.6.2.2472-linux.zip -o sonar-scanner.zip
        unzip sonar-scanner.zip -d /tmp
        export PATH=$PATH:/tmp/sonar-scanner-4.6.2.2472-linux/bin
        sonar-scanner --version  # Controleer of de installatie succesvol was

    - name: Cache SonarCloud dependencies
      uses: actions/cache@v2
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar-${{ hashFiles('**/*.js', '**/*.vb') }}

    - name: Set up SonarCloud
      uses: SonarSource/sonarcloud-github-action@v1
      with:
        projectBaseDir: '.'

      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
