name: SonarCloud Analysis

on:
  push:
    branches:
      - main  # Of een andere branch die je wilt volgen
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    name: SonarCloud analysis
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Cache SonarCloud dependencies
      uses: actions/cache@v2
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar-${{ hashFiles('**/*.js', '**/*.vb') }}

    # Set up SonarCloud
    - name: Set up SonarCloud
      uses: SonarSource/sonarcloud-github-action@v1
      with:
        entryPoint: "/bin/bash"
        args: |
          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
          -Dsonar.organization=${{ secrets.SONAR_ORG }} \
          -Dsonar.host.url=https://sonarcloud.io
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Zet de SONAR_TOKEN als een omgevingsvariabele
