name: SonarQube Analysis

on:
  push:
    branches:
      - main  # of de branch waarop je de analyse wilt uitvoeren

jobs:
  sonarcloud:
    name: Run SonarQube Scanner with Docker
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run SonarScanner in Docker
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: "https://sonarcloud.io"  # Als je dit als secret hebt, kun je ook naar ${{ secrets.SONAR_HOST_URL }} verwijzen
      run: |
        docker run \
          --rm \
          -e SONAR_HOST_URL="${SONAR_HOST_URL}" \
          -e SONAR_TOKEN="${SONAR_TOKEN}" \
          -v "${GITHUB_WORKSPACE}:/usr/src" \
          sonarsource/sonar-scanner-cli \
          -Dsonar.projectKey=elderds16_Software-Quality \
          -Dsonar.sources=src \
          -Dsonar.host.url="${SONAR_HOST_URL}" \
          -Dsonar.login="${SONAR_TOKEN}"
